# This is the name of the workflow as it will appear in the "Actions" tab of your GitHub repository.
name: Deploy to Firebase Hosting

# This section defines when the workflow should run.
# It's configured to run on every 'push' to the 'main' branch.
# If your main branch is named 'master', you should change 'main' to 'master'.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build_and_deploy".
  build_and_deploy:
    # The type of virtual machine that the job will run on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # A job is made up of a sequence of steps.
    steps:
      # Step 1: Check out your repository's code.
      # This downloads your code into the virtual machine so the following steps can use it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Step 2: If your project needs a build step (like with React, Vue, or Svelte),
      # you would uncomment and add those commands here. For a simple HTML/CSS/JS site, this is not needed.
      # - name: Install dependencies and build
      #   run: |
      #     npm install
      #     npm run build

      # Step 3: Deploy to Firebase Hosting.
      # This uses a pre-made action from the Firebase team to handle the deployment.
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # This token is automatically generated by GitHub for the action to interact with your repository.
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          # This is the secret token you added to your repository's settings in Step 2.
          # It authenticates the action with your Firebase project.
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          # The ID of the channel to deploy to. 'live' means your main production site.
          channelId: live
          # VERY IMPORTANT: This MUST be the ID of your Firebase project.
          projectId: journeyman-edge-exams
